export const roomsData = [
  {
    roomId: "101",
    name: "Room 101",
    type: "AC",
    price: 2000,
    beds: "Double Bed",
    badge: "AC",
    amenities: ["WiFi", "TV", "Hot Water", "AC"],
    available: true,
  },
  {
    roomId: "102",
    name: "Room 102",
    type: "Suite AC",
    price: 10000,
    beds: "King Bed",
    badge: "Suite AC",
    amenities: ["WiFi", "TV", "Hot Water", "AC", "Minibar", "Balcony"],
    available: true,
  },
  {
    roomId: "103",
    name: "Room 103",
    type: "AC",
    price: 2000,
    beds: "Double Bed",
    badge: "AC",
    amenities: ["WiFi", "TV", "Hot Water", "AC"],
    available: true,
  },
  {
    roomId: "104",
    name: "Room 104",
    type: "Non-AC",
    price: 1500,
    beds: "Double Bed",
    badge: "Non-AC",
    amenities: ["WiFi", "TV", "Hot Water", "Fan"],
    available: true,
  },
  {
    roomId: "105",
    name: "Room 105",
    type: "Non-AC",
    price: 1500,
    beds: "Single Bed",
    badge: "Non-AC",
    amenities: ["WiFi", "TV", "Hot Water", "Fan"],
    available: true,
  },
  {
    roomId: "106",
    name: "Room 106",
    type: "Non-AC",
    price: 1500,
    beds: "Single Bed",
    badge: "Non-AC",
    amenities: ["WiFi", "TV", "Hot Water", "Fan"],
    available: true,
  },
  {
    roomId: "107",
    name: "Room 107",
    type: "Non-AC",
    price: 1500,
    beds: "Double Bed",
    badge: "Non-AC",
    amenities: ["WiFi", "TV", "Hot Water", "Fan"],
    available: true,
  },
  {
    roomId: "108",
    name: "Room 108",
    type: "AC",
    price: 2000,
    beds: "Double Bed",
    badge: "AC",
    amenities: ["WiFi", "TV", "Hot Water", "AC"],
    available: true,
  },
  {
    roomId: "109",
    name: "Room 109",
    type: "Non-AC",
    price: 1500,
    beds: "Double Bed",
    badge: "Non-AC",
    amenities: ["WiFi", "TV", "Hot Water", "Fan"],
    available: true,
  },
  {
    roomId: "110",
    name: "Room 110",
    type: "Villa",
    price: 2500,
    beds: "Double Bed",
    badge: "Villa",
    amenities: ["WiFi", "TV", "Hot Water", "Fan", "Garden View"],
    available: true,
  },
  {
    roomId: "111",
    name: "Suite AC Premium",
    type: "Suite AC",
    price: 10000,
    beds: "King Bed",
    badge: "Suite Premium",
    amenities: ["WiFi", "TV", "Hot Water", "AC", "Minibar", "Balcony", "Mountain View"],
    available: true,
  },
];
